export const officerTitles: string[] = [
  'RETIRED',
  'FORMER',
  'COUNSEL',
  'FORMERLY',
  'EMERITUS',
  'INTERIM',
  'LEGAL',
  'GENERAL COUNSEL',
  'GC',
  'SECRETARY',
  'CORPORATE SECRETARY',
  'COMPLIANCE',
  'HUMAN RESOURCES',
  'HR',
  'PEOPLE',
  'CHIEF PEOPLE OFFICER',
  'TALENT',
  'CONTROLLER',
  'TREASURER',
  'ACCOUNTING',
  'PAO', // principal accounting officer
  'ADVISOR',
  'CONSULTANT',
  'OBSERVER',
  'SEE REMARKS',
];